import { randomEnum } from "../utils/math";
import { FrameHeader } from "./frame";
import ErrorMessageEn from "./errorMessage.json";

enum ErrorCodes {
  CURRENT_ERROR_250 = "CURRENT_ERROR_250",
  THROTTLE_ERROR_250 = "THROTTLE_ERROR_250",
  PHASE_FAULT_250 = "PHASE_FAULT_250",
  MOTOR_HALL_ERROR_250 = "MOTOR_HALL_ERROR_250",
  BRAKE_ERROR_250 = "BRAKE_ERROR_250",
  OVER_CURRENT_750 = "OVER_CURRENT_750",
  OVER_VOLTAGE_WARNING_750 = "OVER_VOLTAGE_WARNING_750",
  UNDER_VOLTAGE_WARNING_750 = "UNDER_VOLTAGE_WARNING_750",
  BRAKE_ERROR_750 = "BRAKE_ERROR_750",
  THROTTLE_RETURN_ERROR_750 = "THROTTLE_RETURN_ERROR_750",
  THROTTLE_FAILURE_750 = "THROTTLE_FAILURE_750",
  LOW_VOLTAGE_PROTECTION_750 = "LOW_VOLTAGE_PROTECTION_750",
  OVER_VOLTAGE_PROTECTION_750 = "OVER_VOLTAGE_PROTECTION_750",
  MOTOR_HALL_ERROR_750 = "MOTOR_HALL_ERROR_750",
  MOTOR_PHASE_ERROR_750 = "MOTOR_PHASE_ERROR_750",
  MOTOR_TEMP_PROTECTION_750 = "MOTOR_TEMP_PROTECTION_750",
  MOTOR_TEMP_ERROR_750 = "MOTOR_TEMP_ERROR_750",
  CONTROLLER_TEMP_PROTECTION_750 = "CONTROLLER_TEMP_PROTECTION_750",
  CONTROLLER_TEMP_ERROR_750 = "CONTROLLER_TEMP_ERROR_750",
  CURRENT_SENSOR_ERROR_750 = "CURRENT_SENSOR_ERROR_750",
  HEADLIGHT_ERROR_750 = "HEADLIGHT_ERROR_750",
  BRAKE_DETECTION_ERROR_750 = "BRAKE_DETECTION_ERROR_750",
  POWER_DETECTION_15V_ERROR_750 = "POWER_DETECTION_15V_ERROR_750",
  BUTTON_DETECTION_ERROR_750 = "BUTTON_DETECTION_ERROR_750",
  SPEED_SENSOR_ERROR_750 = "SPEED_SENSOR_ERROR_750",
  WDT_ERROR_750 = "WDT_ERROR_750",
}

enum DeviceID {
  CONTROLLER_250 = "CONTROLLER_250",
  CONTROLLER_750 = "CONTROLLER_750",
  SENSOR = "SENSOR",
  BATTERY = "BATTERY",
  HMI = "HMI",
  SMART_LOCK = "SMART_LOCK",
  CONTROL_BOARD = "CONTROL_BOARD",
  JOYSTICK = "JOYSTICK",
  ENVIOLO = "ENVIOLO",
  LIDAR = "LIDAR",
  POWER_SUPPLY_BOARD = "POWER_SUPPLY_BOARD",
}

export type ErrorFrame = {
  id: number;
  createdAt: number; //Date in epoch
  frameHeader: FrameHeader.ERROR;
  deviceID: DeviceID;
  errorCode: ErrorCodes;
};

export const getRandomError = (): ErrorFrame => {
  return {
    id: Date.now(),
    createdAt: Date.now(),
    deviceID: randomEnum(DeviceID),
    errorCode: randomEnum(ErrorCodes),
    frameHeader: FrameHeader.ERROR,
  } as ErrorFrame;
};

interface ErrorMessageMap {
  [key: string]: string;
}

export const getErrorMessage = (errorCode: string, language = "en"): string => {
  const errorMessage = ErrorMessageEn as ErrorMessageMap;
  return errorMessage[errorCode];
};
